# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  
  build:
    environment: 
      name: dev
    env:
        version1: ${{ secrets.TEXT }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET - secret text is - "${{ secrets.TEXT }}" "${{ vars.version1 }}"
      env:
        version1: ${{ secrets.text }}
      run: echo ${{secrets.TEXT}} | sed 's/./& /g'
