# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET - secret text is - "${{ secrets.text }}"
      env:
        version1: ${{ secrets.text }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.'${{ secrets.text }}'
